name: Daily Performance Tests(u8)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Ballerina Build from Nightly Pack
      uses: ballerina-platform/ballerina-action@nightly
      env:
        WORKING_DIR: bal_project
      with:
        args:
          build
